name: "Setup Cpp and Vulkan"
description: "Sets up Cpp and Vulkan"
runs:
  using: "composite"
  steps:
    - name: Set up cpp
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y g++-12 build-essential
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
    - name: Set up Vulkan
      shell: bash
      run: |
        sudo apt install vulkan-tools
        sudo apt install libvulkan-dev
        sudo apt install vulkan-validationlayers-dev spirv-tools
    - name: Set up GLFW
      shell: bash
      run: |
        sudo apt install libglfw3-dev
    - name: Set up GLM
      shell: bash
      run: |
        sudo apt install libglm-dev

