name: "Setup Vulkan"
description: "Sets up Vulkan"
runs:
  using: "composite"
  steps:
    - name: Set up Vulkan
      shell: bash
      run: |
        sudo apt install vulkan-tools
        sudo apt install libvulkan-dev
        sudo apt install vulkan-validationlayers-dev spirv-tools
    - name: Set up GLFW
      shell: bash
      run: |
        sudo apt install libglfw3-dev
    - name: Set up GLM
      shell: bash
      run: |
        sudo apt install libglm-dev
