name: "Continuous Integration"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup cpp and Vulkan
        uses: ./.github/actions/setup
      - name: Build app
        shell: bash
        run: |
          make ci