name: "Continuous Integration"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup cpp
        uses: ./.github/actions/setup-cpp
      - name: Setup Vulkan
        uses: ./.github/actions/setup-vulkan
      - name: Build app
        shell: bash
        run: |
          make build